sudo: required
services:
  - docker

before_install:
  - docker build -t pastiubogdan/react-test -f ./client/Dockerfile.dev ./client

script:
  - - docker run -e CI=true pastiubogdan/react-test npm test

after_success:
  - docker build -t pastiubogdan/multi-client:1.0.0 ./client
  - docker build -t pastiubogdan/multi-nginx:1.0.0 ./nginx
  - docker build -t pastiubogdan/multi-server:1.0.0 ./server
  - docker build -t pastiubogdan/multi-worker:1.0.0 ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pastiubogdan/multi-client:1.0.0
  - docker push pastiubogdan/multi-nginx:1.0.0
  - docker push pastiubogdan/multi-server:1.0.0
  - docker push pastiubogdan/multi-worker:1.0.0
